name: Semantic Release

on:
  push:
    branches:
    - "master"

jobs:
  release:
    container:
      image: node:10-alpine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Git
      run: apk add git
    - name: Initialize
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm ci
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm test
    - name: Release Codebase
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run release
